name: CI - Backend Docker Testing

on:
  push:
    branches:
      - '*'

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      
      - name: Login to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_TOKEN }}
      
      - name: Build and Push Docker Image
        run: |
          docker build -t ${{ secrets.DOCKER_USERNAME }}/cs360_backend_image_test:latest -f backend/Dockerfile .
          docker push ${{ secrets.DOCKER_USERNAME }}/cs360_backend_image_test:latest
      
      - name: Pull and Run Container
        run: |
          docker pull ${{ secrets.DOCKER_USERNAME }}/cs360_backend_image_test:latest
          docker run -d --name test-backend-container \
            --memory="8g" \
            --memory-swap="16g" \
            ${{ secrets.DOCKER_USERNAME }}/cs360_backend_image_test:latest \
            tail -f /dev/null
      
      - name: Run Backend Tests
        run: |
          docker ps
          docker exec test-backend-container npm run test-back
      
      - name: Cleanup
        if: always()
        run: |
          docker stop test-backend-container || true
          docker rm test-backend-container || true