name: CI - Test Source Code and Docker Image

on:
  push:
    branches:
      - '*'

jobs:
  test-backend-source-code:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      
      - uses: actions/setup-node@v3
        with:
          node-version: 20
      
      - name: Install Backend Dependencies
        run: |
          cd backend
          npm install
      
      - name: Run Jest Tests
        run: |
          cd backend
          npm run test-back

  build-backend-docker:
    needs: test-backend-source-code
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      
      - name: Login to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_TOKEN }}
      
      - name: Build and Push Docker Image
        run: |
          docker build -t ${{ secrets.DOCKER_USERNAME }}/cs360_backend_image_test:latest -f backend/Dockerfile .
          docker push ${{ secrets.DOCKER_USERNAME }}/cs360_backend_image_test:latest
      
      - name: Run Docker Container
        run: |
          docker pull ${{ secrets.DOCKER_USERNAME }}/cs360_backend_image_test:latest
          docker run -d --name test-backend-container \
            --memory="8g" \
            --memory-swap="16g" \
            ${{ secrets.DOCKER_USERNAME }}/cs360_backend_image_test:latest \
            sh -c "sleep 30 && npm run test-back"
      
      - name: Container Logs
        if: failure()
        run: docker logs test-backend-container
      
      - name: Cleanup Container
        if: always()
        run: |
          docker stop test-backend-container || true
          docker rm test-backend-container || true